### ISSUE TITLE
Some ideas to help mappers map the bicycle network

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-data#1]
* Create a map when you can choose to display only **one** road at a time (on top on OSM baselayer)
* Create a page with 2 synced maps (when you zoom/pan on one, it should zoom on the other one as well) to compare data :
    * Map on the left = Brussels bicycle network
    * Map on the right = OSM the data

It's possible with basic HTML/JavaScript so you can use GitHub pages to host it.

**Comment by DDieter** [comment]
Probably not going to do the 2 synced maps, but we have the Brussels cycling network and OSM data one map available as layers so I'm going to close this.
