### ISSUE TITLE
Manually compare data and update wiki

### ISSUE THREAD

**Issue by DDieter** [oSoc17/rideaway-data#5]
First do another manual comparison of the data and update the [OSM wiki](http://wiki.openstreetmap.org/wiki/WikiProject_Belgium/Cycle_Routes#Itin.C3.A9raires_Cyclables_R.C3.A9gionaux_-_Gewestelijke_Fietsroute).

Also identify issues with the metadata and provide a detailed plan for fixing and completing the OSM data.

**Comment by damianrbsn** [comment]
```
CASE
	WHEN part IS NULL THEN icr
	WHEN part is NOT NULL THEN icr || lower(part)
	
END
```
