### ISSUE TITLE
Brussels Data Preprocessing - New field

### ISSUE THREAD

**Issue by damianrbsn** [oSoc17/rideaway-data#7]
goal: writing an expression for 'field calculator' that combines 'icr' with 'part'

the field 'route' already exists

1. create a new field called 'route' - [ideas for a new name?]
2. combines the string 'icr' with a lower case 'part'

my simple solution of  icr || lower(part) doesn't work with 'part' is NULL. fyi the fields of 'icr' and 'part' are in already in a string format.

new idea: can an expression be written that creates a new field of route. it would better automatic the process. thanks.

**Comment by DDieter** [comment]
```
CASE
	WHEN part IS NULL THEN icr
	WHEN part is NOT NULL THEN icr || lower(part)
END
```
